In [53]:
import pandas as pd
df = pd.read_csv('ex1.csv')
print(df)

   a  b  c  d message
0  1  2  3  4   hello
1  5  6  7  8  worlds


In [5]:
uf = pd.read_csv('C:\\Users\\dpriyareddypothul\\downloads\\titanic-data.csv')
print(uf)

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ... 

In [6]:
print(uf.head(5))

   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [7]:
print(df.head(4))

   a  b  c  d message
0  1  2  3  4   hello
1  5  6  7  8  worlds


In [8]:
print(uf['Name'].dtypes)
print(uf['Ticket'].dtypes)
print(uf['Pclass'].dtypes)

object
object
int64


In [9]:
print(df)

   a  b  c  d message
0  1  2  3  4   hello
1  5  6  7  8  worlds


In [10]:
df= pd.read_csv("C:\\Users\\dpriyareddypothul\\documents\\M1M2\\DS-1\\ex1.csv")
print(df)

  Row1 Row2 Row3 Row4     Row5
0    a    b    c    d  message
1    1    2    3    4    hello
2    5  NaN    7    8   worlds
3    8    5    4    5      NaN
4  NaN   5t    h    e      jhj


In [11]:
attr = "C:\\Users\\dpriyareddypothul\\documents\\M1M2\\DS-1\\ex1.csv"
dfp = pd.read_csv(attr,skiprows=1,na_values=["no info","."])
print(dfp)

     a    b  c  d message
0  1.0    2  3  4   hello
1  5.0  NaN  7  8  worlds
2  8.0    5  4  5     NaN
3  NaN   5t  h  e     jhj


In [12]:
attr = "C:\\Users\\dpriyareddypothul\\documents\\M1M2\\DS-1\\ex1.csv"
dfp = pd.read_csv(attr,header=None)
print(dfp)

      0     1     2     3        4
0  Row1  Row2  Row3  Row4     Row5
1     a     b     c     d  message
2     1     2     3     4    hello
3     5   NaN     7     8   worlds
4     8     5     4     5      NaN
5   NaN    5t     h     e      jhj


In [13]:
attr = "C:\\Users\\dpriyareddypothul\\documents\\M1M2\\DS-1\\ex1.csv"
dfp = pd.read_csv(attr,skiprows=1,names=['A1','A2','A3','A4','TEXT'])
print(dfp)

    A1   A2 A3 A4     TEXT
0    a    b  c  d  message
1    1    2  3  4    hello
2    5  NaN  7  8   worlds
3    8    5  4  5      NaN
4  NaN   5t  h  e      jhj


In [14]:
attr = "C:\\Users\\dpriyareddypothul\\documents\\M1M2\\DS-1\\ex1.csv"
dfp = pd.read_csv(attr,skiprows=1,names=['A1','A2','A3','A4','TEXT'], index_col='TEXT')
print(dfp)

          A1   A2 A3 A4
TEXT                   
message    a    b  c  d
hello      1    2  3  4
worlds     5  NaN  7  8
NaN        8    5  4  5
jhj      NaN   5t  h  e


In [15]:
attr = "C:\\Users\\dpriyareddypothul\\documents\\M1M2\\DS-1\\ex1.csv"
dfp = pd.read_csv(attr,skiprows=1,names=['A1','A2','A3','A4','TEXT'], 
                  index_col=['A4','A3','A1','A2'])
print(dfp)

                  TEXT
A4 A3 A1  A2          
d  c  a   b    message
4  3  1   2      hello
8  7  5   NaN   worlds
5  4  8   5        NaN
e  h  NaN 5t       jhj


In [16]:
import pandas as pd
obj= pd.Series([4,7,5,6])
print(obj)

0    4
1    7
2    5
3    6
dtype: int64


In [17]:
obj.values

array([4, 7, 5, 6], dtype=int64)

In [18]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [19]:
obj2= pd.Series([4,7,6,5],index=['a','c','l','m'])
print(obj2)

a    4
c    7
l    6
m    5
dtype: int64


In [20]:
obj2.index

Index(['a', 'c', 'l', 'm'], dtype='object')

In [21]:
obj2[['a','c','m']]

a    4
c    7
m    5
dtype: int64

In [22]:
obj2

a    4
c    7
l    6
m    5
dtype: int64

In [23]:
obj2[obj2>6]

c    7
dtype: int64

In [24]:
obj2*2

a     8
c    14
l    12
m    10
dtype: int64

In [25]:
import numpy as np
print('mean is',np.mean(obj2))
print('median is', np.median(obj2))

mean is 5.5
median is 5.5


In [26]:
obj2

a    4
c    7
l    6
m    5
dtype: int64

In [27]:
7 in obj2

False

In [28]:
'b' in obj2

False

In [29]:
'c' in obj2

True

In [30]:
import pandas as pd
sdata = {'ohio':3500,'Texas':7100,'Oregon':1600,'Utah':5000}
obj3= pd.Series(sdata)
print(obj3)

ohio      3500
Texas     7100
Oregon    1600
Utah      5000
dtype: int64


In [31]:
states = {'California','Virginia','ohio','Texas','Oregon','Utah'}
obj4 = pd.Series(sdata, index=states)
print(obj4)

Oregon        1600.0
Texas         7100.0
ohio          3500.0
California       NaN
Virginia         NaN
Utah          5000.0
dtype: float64


In [32]:
#isnull and notfull functions in pandas should be used to detect missing data
pd.isnull(obj4)

Oregon        False
Texas         False
ohio          False
California     True
Virginia       True
Utah          False
dtype: bool

In [33]:
pd.notnull(obj4)

Oregon         True
Texas          True
ohio           True
California    False
Virginia      False
Utah           True
dtype: bool

In [34]:
print('obj3 data\n',obj3)
print('\n obj4 data\n',obj4)
print('\n\n', obj3+obj4)

obj3 data
 ohio      3500
Texas     7100
Oregon    1600
Utah      5000
dtype: int64

 obj4 data
 Oregon        1600.0
Texas         7100.0
ohio          3500.0
California       NaN
Virginia         NaN
Utah          5000.0
dtype: float64


 California        NaN
Oregon         3200.0
Texas         14200.0
Utah          10000.0
Virginia          NaN
ohio           7000.0
dtype: float64


In [35]:
print(obj3.name)
obj3.name= 'Data 3 for test'
print(obj3.name)
print(obj3.index.name)

None
Data 3 for test
None


In [36]:
obj3.index=['23','24','25','26']
print(obj3)

23    3500
24    7100
25    1600
26    5000
Name: Data 3 for test, dtype: int64


#DataFrames

# DataFrame represents a tabular, spreadsheet-like data structure containing an ordered collection of columns,each of which can be of different value type(numeric, string, booleah etc.).DataFrame basically stores data as one or more two dimensional blocks.

In [37]:
data = {'state':['Ohio','Ohio','nevada','Nevada'],
       'year':[2000,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.9]}
frame = pd.DataFrame(data)
print(frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2  nevada  2002  3.6
3  Nevada  2003  2.9


In [38]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','date'])
print(frame2)

   year   state  pop date
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002  nevada  3.6  NaN
3  2003  Nevada  2.9  NaN


In [39]:
print(frame2.columns)

Index(['year', 'state', 'pop', 'date'], dtype='object')


In [40]:
print(frame2['state'])

0      Ohio
1      Ohio
2    nevada
3    Nevada
Name: state, dtype: object


In [41]:
print(frame2.year)

0    2000
1    2001
2    2002
3    2003
Name: year, dtype: int64


In [42]:
print(frame.iloc[3])

state    Nevada
year       2003
pop         2.9
Name: 3, dtype: object


In [43]:
frame2.date = 'Dec 25'
print(frame2)
frame2['date'] = '12/25'
print('\n\n',frame2)

   year   state  pop    date
0  2000    Ohio  1.5  Dec 25
1  2001    Ohio  1.7  Dec 25
2  2002  nevada  3.6  Dec 25
3  2003  Nevada  2.9  Dec 25


    year   state  pop   date
0  2000    Ohio  1.5  12/25
1  2001    Ohio  1.7  12/25
2  2002  nevada  3.6  12/25
3  2003  Nevada  2.9  12/25


In [44]:
import numpy as np
randoml = np.arange(4)
print(randoml)
frame2['randoml'] = randoml
print(frame2)

[0 1 2 3]
   year   state  pop   date  randoml
0  2000    Ohio  1.5  12/25        0
1  2001    Ohio  1.7  12/25        1
2  2002  nevada  3.6  12/25        2
3  2003  Nevada  2.9  12/25        3


In [45]:
frame2.columns = ['year','state','pop','date','debt']
frame3 = frame2.rename(columns={'year':'years','date':'dym'})
print(frame2)
print('\n\n',frame3)

   year   state  pop   date  debt
0  2000    Ohio  1.5  12/25     0
1  2001    Ohio  1.7  12/25     1
2  2002  nevada  3.6  12/25     2
3  2003  Nevada  2.9  12/25     3


    years   state  pop    dym  debt
0   2000    Ohio  1.5  12/25     0
1   2001    Ohio  1.7  12/25     1
2   2002  nevada  3.6  12/25     2
3   2003  Nevada  2.9  12/25     3


In [46]:
print(frame2)

   year   state  pop   date  debt
0  2000    Ohio  1.5  12/25     0
1  2001    Ohio  1.7  12/25     1
2  2002  nevada  3.6  12/25     2
3  2003  Nevada  2.9  12/25     3


In [52]:
val= pd.Series([1,2,3,4],index=[2,3,1,0])
frame2['debt']=val
print(frame2)


   year   state  pop  debt
0  2000    Ohio  1.5     4
1  2001    Ohio  1.7     3
2  2002  nevada  3.6     1
3  2003  Nevada  2.9     2


In [48]:
del frame2['date']
print(frame2)

   year   state  pop  debt
0  2000    Ohio  1.5     4
1  2001    Ohio  1.7     3
2  2002  nevada  3.6     1
3  2003  Nevada  2.9     2


In [51]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [50]:
frame2.values

array([[2000, 'Ohio', 1.5, 4],
       [2001, 'Ohio', 1.7, 3],
       [2002, 'nevada', 3.6, 1],
       [2003, 'Nevada', 2.9, 2]], dtype=object)