In [1]:
import numpy as np

In [2]:
numbers = np.array([1,2,3,4,5])
print(numbers)

[1 2 3 4 5]


In [4]:
print('to find avegare of the numbers')
print('mean:',np.mean(numbers))
print('median',np.median(numbers))
print('standard deviation',np.std(numbers))

to find avegare of the numbers
mean: 3.0
median 3.0
standard deviation 1.4142135623730951


In [15]:
    array = np.array([1,2,3,4],float)
    print(array)
    print(" ")
    array = np.array([[1,2,3],[4,5,6]],float)
    print(array)

[1. 2. 3. 4.]
 
[[1. 2. 3.]
 [4. 5. 6.]]


In [20]:
print(array)
print ('\n',array[1][2])

array[1][2]=7

print ('\n',array)

[[1. 2. 3.]
 [4. 5. 7.]]

 7.0

 [[1. 2. 3.]
 [4. 5. 7.]]


In [30]:
# creating a dictinery and then data frames
import pandas as pd
d = { 'name': pd.Series(['Bob','com','Heikken','allen'],index=['a','b','c','d']),
       'age': pd.Series([22,38,26,35],index=['a','b','c','d']),
       'Fare': pd.Series([7.25,71.83,8.05],index=['a','b','d']),
     'survived:': pd.Series([False,True,True,False],index=['a','b','c','d'])}
df = pd.DataFrame(d)
print(df)

      name  age   Fare  survived:
a      Bob   22   7.25      False
b      com   38  71.83       True
c  Heikken   26    NaN       True
d    allen   35   8.05      False


In [32]:
# playing with series in Pandas
import pandas as pd
series = pd.Series(['Dave','chenug','udacity',42,-1756])
print(series)


0       Dave
1     chenug
2    udacity
3         42
4      -1756
dtype: object


In [37]:
series2 = pd.Series(['Dave','Cheung',359,9001],
                   index=['Instructor','Curriculum Mgr','Course Num','Power level'])
print(series2)

Instructor          Dave
Curriculum Mgr    Cheung
Course Num           359
Power level         9001
dtype: object


In [44]:
print( series2['Instructor'])
print( series2[['Course Num','Power level','Instructor']])

Dave
Course Num      359
Power level    9001
Instructor     Dave
dtype: object


In [49]:
cuteness = pd.Series([1,2,3,4,5],index=['Cockroach','Fish','Mini Pig','Puppy','Kitten'])
print(cuteness)
print('with cuteness greater than 3\n',cuteness>3)
print( cuteness[cuteness>3])

Cockroach    1
Fish         2
Mini Pig     3
Puppy        4
Kitten       5
dtype: int64
with cuteness greater than 3
 Cockroach    False
Fish         False
Mini Pig     False
Puppy         True
Kitten        True
dtype: bool
Puppy     4
Kitten    5
dtype: int64


In [50]:
data = {'years' : [2010,2011,2012,2013,2014,2015],
       'team':['Bears','Bears','Pacekrs','Packers','Lions','Lions'],
       'wins':[11,8,10,6,10,11],
       'losses':[5,8,6,7,5,4]}
football= pd.DataFrame(data)
print(football)

   years     team  wins  losses
0   2010    Bears    11       5
1   2011    Bears     8       8
2   2012  Pacekrs    10       6
3   2013  Packers     6       7
4   2014    Lions    10       5
5   2015    Lions    11       4


In [51]:
print(football.dtypes)

years      int64
team      object
wins       int64
losses     int64
dtype: object


In [52]:
print(football.describe())

             years       wins    losses
count     6.000000   6.000000  6.000000
mean   2012.500000   9.333333  5.833333
std       1.870829   1.966384  1.471960
min    2010.000000   6.000000  4.000000
25%    2011.250000   8.500000  5.000000
50%    2012.500000  10.000000  5.500000
75%    2013.750000  10.750000  6.750000
max    2015.000000  11.000000  8.000000


In [53]:
print(football.head())

   years     team  wins  losses
0   2010    Bears    11       5
1   2011    Bears     8       8
2   2012  Pacekrs    10       6
3   2013  Packers     6       7
4   2014    Lions    10       5


In [54]:
print(football.tail())

   years     team  wins  losses
1   2011    Bears     8       8
2   2012  Pacekrs    10       6
3   2013  Packers     6       7
4   2014    Lions    10       5
5   2015    Lions    11       4


In [55]:
print(df)

      name  age   Fare  survived:
a      Bob   22   7.25      False
b      com   38  71.83       True
c  Heikken   26    NaN       True
d    allen   35   8.05      False


In [59]:
print('to access teh columns of the df table\n')
print(df['name'])
print('\n access multiple columns')
print(df[['name','age']])

to access teh columns of the df table

a        Bob
b        com
c    Heikken
d      allen
Name: name, dtype: object

 access multiple columns
      name  age
a      Bob   22
b      com   38
c  Heikken   26
d    allen   35


In [62]:
print('to access using index')
print(df.loc['c'])

to access using index
name         Heikken
age               26
Fare             NaN
survived:       True
Name: c, dtype: object


In [64]:
print(df[df['age']>=30])

    name  age   Fare  survived:
b    com   38  71.83       True
d  allen   35   8.05      False


In [66]:
print(df['survived:'][df['age']>=30])

b     True
d    False
Name: survived:, dtype: bool


In [67]:
print(football)

   years     team  wins  losses
0   2010    Bears    11       5
1   2011    Bears     8       8
2   2012  Pacekrs    10       6
3   2013  Packers     6       7
4   2014    Lions    10       5
5   2015    Lions    11       4


In [68]:
print(football['years'])

0    2010
1    2011
2    2012
3    2013
4    2014
5    2015
Name: years, dtype: int64


In [69]:
print(football.team)

0      Bears
1      Bears
2    Pacekrs
3    Packers
4      Lions
5      Lions
Name: team, dtype: object


In [71]:
print(football[['years','team','losses','wins']])

   years     team  losses  wins
0   2010    Bears       5    11
1   2011    Bears       8     8
2   2012  Pacekrs       6    10
3   2013  Packers       7     6
4   2014    Lions       5    10
5   2015    Lions       4    11


In [72]:
print(football.iloc[[2]])

   years     team  wins  losses
2   2012  Pacekrs    10       6


In [74]:
print(football.loc[2])

years        2012
team      Pacekrs
wins           10
losses          6
Name: 2, dtype: object


In [75]:
print(football[3:5])

   years     team  wins  losses
3   2013  Packers     6       7
4   2014    Lions    10       5


In [78]:
print(football[football.wins>10])

   years   team  wins  losses
0   2010  Bears    11       5
5   2015  Lions    11       4


In [80]:
print( football[(football.wins>10) & (football.team == 'Lions')])

   years   team  wins  losses
5   2015  Lions    11       4


In [87]:
import numpy as np
import pandas as pd
one = [1,2,3]
two = [1,2,34]

dict4 = {'one':pd.Series(one),'two':pd.Series(two)}
df3= pd.DataFrame(dict4)
print(df3)

   one  two
0    1    1
1    2    2
2    3   34


In [90]:
print(df3.apply(np.mean))

print(df3.apply(np.std))

one     2.000000
two    12.333333
dtype: float64
one     0.816497
two    15.326085
dtype: float64


In [94]:
print(football)


   years     team  wins  losses
0   2010    Bears    11       5
1   2011    Bears     8       8
2   2012  Pacekrs    10       6
3   2013  Packers     6       7
4   2014    Lions    10       5
5   2015    Lions    11       4


In [95]:
b=np.mean(one)
print(b)

2.0


In [109]:
countries = ['Russian Fed.', 'Norway', 'Canada', 'United States',
                 'Netherlands', 'Germany', 'Switzerland', 'Belarus',
                 'Austria', 'France', 'Poland', 'China', 'Korea', 
                 'Sweden', 'Czech Republic', 'Slovenia', 'Japan',
                 'Finland', 'Great Britain', 'Ukraine', 'Slovakia',
                 'Italy', 'Latvia', 'Australia', 'Croatia', 'Kazakhstan']

gold = [13, 11, 10, 9, 8, 8, 6, 5, 4, 4, 4, 3, 3, 2, 2, 2, 1, 1, 1, 1, 1,30, 10, 20, 0, 0]
silver = [11, 5, 10, 7, 7, 6, 3, 0, 8, 4, 1, 4, 3, 7, 4, 2, 4, 3, 1, 0, 0, 2, 2, 2, 1, 0]
bronze = [9, 10, 5, 12, 9, 5, 2, 1, 5, 7, 1, 2, 2, 6, 2, 4, 3, 1, 2, 1, 0, 6, 2, 1, 0, 1]
    
olympic_medal_counts = {'country_name':countries,
                            'gold': pd.Series(gold),
                            'silver': pd.Series(silver),
                            'bronze': pd.Series(bronze)}    
olympic_medal_counts_df = pd.DataFrame(olympic_medal_counts)
a= np.mean(gold)
b= np.mean(silver)
c= np.mean(bronze)
    
avg_medal_count = pd.Series([a,b,c])
print( avg_medal_count)

0    6.115385
1    3.730769
2    3.807692
dtype: float64


In [111]:
print('one line code for above can be as below: \n')
avg_medal_count = olympic_medal_counts_df[['gold','silver','bronze']].apply(np.mean)
print(avg_medal_count)

one line code for above can be as below: 

gold      6.115385
silver    3.730769
bronze    3.807692
dtype: float64
